language: rust
rust:
  - 1.32.0
  - 1.33.0
  - stable
install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy -- -D warnings
  - cargo test
  - cargo package
