[package]
name = "whatlang"
version = "0.2.0"
authors = ["Sergey Potapov <blake131313@gmail.com>"]
description = "Natural language detection library. Identifies language of a given text."
keywords = ["language", "nlp", "lang", "whatlang", "text"]
license = "MIT"
repository = "https://github.com/greyblake/whatlang-rs"
homepage = "https://github.com/greyblake/whatlang-rs"
documentation = "https://github.com/greyblake/whatlang-rs"
readme = "README.md"
categories = ["text-processing", "algorithms"]
include = [
    "src/**/*",
    "test/**/*",
    "Cargo.toml",
    "README.md"
]

[badges]
travis-ci = { repository = "greyblake/whatlang-rs", branch = "master" }

[dev-dependencies]
rustc-serialize = "0.3"
